web:
  restart: always
  image: dockerrepo.eionet.europa.eu:5000/eprtr/eprtr.cms:latest
  ports:
    - "4180:8080"
    - "4109:8009"
  environment:
    - CATALINA_OPTS="-Djava.security.egd=file:/dev/./urandom" "-Dcmsdb.driver=net.sourceforge.jtds.jdbc.Driver" "-Dcmsdb.url=jdbc:jtds:sqlserver://dbhost/EPRTRcms" "-Dcmsdb.username=username" "-Dcmsdb.password=password" "-Dstorage.dir=/var/local/eprtr"
  volumes:
    - /etc/localtime:/etc/localtime:ro # Share timezone data with host
  hostname: eprtr-cms
# mem_limit: 100M
